/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiClient;
import io.swagger.client.ApiResponse;
import io.swagger.client.model.UserDTO;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Logger;

/**
 * API tests for AuthControllerApi
 */
public class AuthControllerApiTest {

    static final Logger logger = Logger.getLogger(AuthControllerApiTest.class.getName());

    private final ApiClient apiClient = new ApiClient();
    private final AuthControllerApi api = new AuthControllerApi(apiClient);
    
    @Test
    public void testLogin_Nominal() throws Exception {
        // Define Input
        UserDTO requestUser = new UserDTO();
        requestUser.setLogin("jdupont");
        requestUser.setPassword("jdupont");

        // Call API
        ApiResponse<UserDTO> response = api.loginUsingPOSTWithHttpInfo(requestUser);

        assertEquals(200, response.getStatusCode());
        assertEquals(1, response.getData().getId());
    }

    @Test
    public void testLogin_() throws Exception {
        // Define Input
        UserDTO requestUser = new UserDTO();
        requestUser.setLogin("jdupont");
        requestUser.setPassword("jdupont");

        // Call API
        UserDTO response = api.loginUsingPOST(requestUser);

        assertEquals(1, response.getId());
    }
    
    /**
     * logoutUser
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void logoutUserUsingPOSTTest() throws Exception {
        
        Object response = api.logoutUserUsingPOST();

        // TODO: test validations
    }
    
}
