/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiClient;
import io.swagger.client.model.ProjectDTO;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;


import java.util.logging.Logger;

/**
 * API tests for ProjectControllerApi
 */
public class ProjectControllerApiTest {

    static final Logger logger = Logger.getLogger(ProjectControllerApiTest.class.getName());

    private final ApiClient apiClient = new ApiClient();
    private final ProjectControllerApi api = new ProjectControllerApi();
    private final ApiTestingTools apiTestingTools = new ApiTestingTools(apiClient);

    @AfterEach
    public void tearDown() throws Exception {
        apiTestingTools.logout();
    }
    
    @Test
    public void testUpdateProject() throws Exception {
        ProjectDTO projectDTO = null;
        Integer projectId = null;
        Integer teamId = null;
        Integer userId = null;
        ProjectDTO response = api.updateProjectUsingPUT(projectDTO, projectId, teamId, userId);

        // TODO: test validations
    }
    
}
