/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.TeamMemberDTO;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TeamMemberControllerApi
 */
public class TeamMemberControllerApiTest {

    private final TeamMemberControllerApi api = new TeamMemberControllerApi();

    
    /**
     * get
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUsingGETTest() throws Exception {
        Integer id = null;
        TeamMemberDTO response = api.getUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * list
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listUsingGETTest() throws Exception {
        List<TeamMemberDTO> response = api.listUsingGET();

        // TODO: test validations
    }
    
    /**
     * setBonusPenalty
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void setBonusPenaltyUsingPOSTTest() throws Exception {
        Integer bonus = null;
        Integer id = null;
        TeamMemberDTO response = api.setBonusPenaltyUsingPOST(bonus, id);

        // TODO: test validations
    }
    
}
