/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.TeamDTO;
import io.swagger.client.model.TeamMemberDTO;
import io.swagger.client.model.UserDTO;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TeamControllerApi
 */
public class TeamControllerApiTest {

    private final TeamControllerApi api = new TeamControllerApi();

    
    /**
     * applyInATeam
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void applyInATeamUsingPUTTest() throws Exception {
        Integer idTeam = null;
        Integer idUser = null;
        UserDTO response = api.applyInATeamUsingPUT(idTeam, idUser);

        // TODO: test validations
    }
    
    /**
     * createTeams
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createTeamsUsingPUTTest() throws Exception {
        Integer nbTeams = null;
        List<TeamDTO> response = api.createTeamsUsingPUT(nbTeams);

        // TODO: test validations
    }
    
    /**
     * getAllTeamMembersOfTeamById
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllTeamMembersOfTeamByIdUsingGETTest() throws Exception {
        Integer idTeam = null;
        List<TeamMemberDTO> response = api.getAllTeamMembersOfTeamByIdUsingGET(idTeam);

        // TODO: test validations
    }
    
    /**
     * getAllTeams
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllTeamsUsingGETTest() throws Exception {
        List<TeamDTO> response = api.getAllTeamsUsingGET();

        // TODO: test validations
    }
    
    /**
     * getTeamById
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTeamByIdUsingGETTest() throws Exception {
        Integer idTeam = null;
        TeamDTO response = api.getTeamByIdUsingGET(idTeam);

        // TODO: test validations
    }
    
}
