/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.UserDTO;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserControllerApi
 */
public class UserControllerApiTest {

    private final UserControllerApi api = new UserControllerApi();

    
    /**
     * add
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addUsingPUTTest() throws Exception {
        UserDTO userDto = null;
        String response = api.addUsingPUT(userDto);

        // TODO: test validations
    }
    
    /**
     * get
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUsingGET1Test() throws Exception {
        Integer id = null;
        UserDTO response = api.getUsingGET1(id);

        // TODO: test validations
    }
    
    /**
     * list
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listUsingGET1Test() throws Exception {
        List<UserDTO> response = api.listUsingGET1();

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateUsingPOSTTest() throws Exception {
        UserDTO userDto = null;
        String response = api.updateUsingPOST(userDto);

        // TODO: test validations
    }
    
}
