# first 8 char of the SHA commit : CI_COMMIT_SHORT_SHA
# name of the targetted branch of the MR : CI_MERGE_REQUEST_TARGET_BRANCH_NAME

stages:
  - build
  - test
  - sonar
  - deploy

variables:
  MAVEN_OPTS: "-Dhttp.proxyHost=192.168.4.8 -Dhttp.proxyPort=3128 -Dhttps.proxyHost=192.168.4.8 -Dhttps.proxyPort=3128 -Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

before_script:
  - export https_proxy=http://192.168.4.8:3128/
  - export http_proxy=http://192.168.4.8:3128/

angular-build:
  stage: build
  image: node:16.19.1-alpine3.17
  script:
    - cd front
    - npm install
    - npm install -g @angular/cli
    - ng build
  artifacts:
    paths:
      - front/dist
    expire_in: 1 hrs
  cache:
    paths:
      - front/node_modules
      - front/.angular/cache

java-build:
  stage: build
  image: maven:3.8.1-jdk-11
  script:
    - cd back
    - curl https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.7.9/spring-boot-starter-parent-2.7.9.pom
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS clean package -DskipTests=true
  artifacts:
    name: "Maven artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    paths:
      - back/target/taf.war
    expire_in: 1 hrs
  cache:
    paths:
      - .m2/repository

junit-test:
  stage: test
  image: maven:3.8.1-jdk-11
  script:
    - cd back
    - curl https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.7.9/spring-boot-starter-parent-2.7.9.pom
    - mvn compile test
  artifacts:
    reports:
      junit: back/target/surefire-reports/TEST*.xml
    paths:
      - back/target/site/jacoco
  cache:
    paths:
      - .m2/repository

# Tests d'intégrations
# robotframework-test:
#   stage: test
#   ...

quality-dev:
  stage: sonar
  image: maven:3.8.1-jdk-11
  script:
    - cd back
    - mvn clean install -DskipTests=true
    - mvn validate sonar:sonar -Pcoverage -Dsonar.projectName=Team3_DevBranch -Dsonar.projectKey=Team3_DevBranch_Project -Dsonar.host.url=http://172.24.1.1:9000/sonar -Dsonar.login=f7545cc5cdd47846233306d2ee6e1430e1233fd3
  cache:
    paths:
      - .m2/repository
  only:
    - dev
  
quality-prod:
  stage: sonar
  image: maven:3.8.1-jdk-11
  script:
    - cd back
    - mvn clean install -DskipTests=true
    - mvn validate sonar:sonar -Pcoverage -Dsonar.projectName=Team3_MasterBranch -Dsonar.projectKey=Team3_MasterBranch_Project -Dsonar.host.url=http://172.24.1.1:9000/sonar -Dsonar.login=66a042836678156de40eac28c940b009324df42c
  cache:
    paths:
      - .m2/repository
  only:
    - master