/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.TeamDTO;
import java.io.IOException;

/**
 * ProjectDTO
 */
public class ProjectDTO {
  @SerializedName("description")
  private String description = null;

  @SerializedName("idProject")
  private Integer idProject = null;

  @SerializedName("isValidated")
  private Boolean isValidated = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("teamDev")
  private TeamDTO teamDev = null;

  @SerializedName("teamValidation")
  private TeamDTO teamValidation = null;

  public ProjectDTO description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ProjectDTO idProject(Integer idProject) {
    this.idProject = idProject;
    return this;
  }

   /**
   * Get idProject
   * @return idProject
  **/
  @ApiModelProperty(value = "")
  public Integer getIdProject() {
    return idProject;
  }

  public void setIdProject(Integer idProject) {
    this.idProject = idProject;
  }

  public ProjectDTO isValidated(Boolean isValidated) {
    this.isValidated = isValidated;
    return this;
  }

   /**
   * Get isValidated
   * @return isValidated
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsValidated() {
    return isValidated;
  }

  public void setIsValidated(Boolean isValidated) {
    this.isValidated = isValidated;
  }

  public ProjectDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ProjectDTO teamDev(TeamDTO teamDev) {
    this.teamDev = teamDev;
    return this;
  }

   /**
   * Get teamDev
   * @return teamDev
  **/
  @ApiModelProperty(value = "")
  public TeamDTO getTeamDev() {
    return teamDev;
  }

  public void setTeamDev(TeamDTO teamDev) {
    this.teamDev = teamDev;
  }

  public ProjectDTO teamValidation(TeamDTO teamValidation) {
    this.teamValidation = teamValidation;
    return this;
  }

   /**
   * Get teamValidation
   * @return teamValidation
  **/
  @ApiModelProperty(value = "")
  public TeamDTO getTeamValidation() {
    return teamValidation;
  }

  public void setTeamValidation(TeamDTO teamValidation) {
    this.teamValidation = teamValidation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectDTO projectDTO = (ProjectDTO) o;
    return Objects.equals(this.description, projectDTO.description) &&
        Objects.equals(this.idProject, projectDTO.idProject) &&
        Objects.equals(this.isValidated, projectDTO.isValidated) &&
        Objects.equals(this.name, projectDTO.name) &&
        Objects.equals(this.teamDev, projectDTO.teamDev) &&
        Objects.equals(this.teamValidation, projectDTO.teamValidation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, idProject, isValidated, name, teamDev, teamValidation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectDTO {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    idProject: ").append(toIndentedString(idProject)).append("\n");
    sb.append("    isValidated: ").append(toIndentedString(isValidated)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    teamDev: ").append(toIndentedString(teamDev)).append("\n");
    sb.append("    teamValidation: ").append(toIndentedString(teamValidation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

